#   Depending on terminal mode, tmux/tmate will interpret escape sequences as
#   function or meta key sequences. The default delay before interpreting Esc
#   as bare Esc is 500 ms which is annoyingly perceptable. (This doesn't affect
#   Vim or Bash for some reason, but does affect Claude Code, Kakone, etc.)
set -s escape-time 10

#   Switch prefix to C-a.
set-option -g prefix C-a
unbind-key C-b              # prefix + Ctrl-B does nothing
bind-key C-a send-prefix    # prefix + Ctrl-A sends Ctrl-A

#   In theory this is needed to pass the custom urxvt code for Shift-Enter (see
#   .Xresources). In practice it's not needed in tmate and doesn't work in tmux.
#set -s extended-keys on

# Enable italics per:
# • https://github.com/tmux/tmux/wiki/FAQ
# • https://github.com/tmate-io/tmate/blob/master/FAQ
# Test with: echo "foo$(tput sitm)bar$(tput ritm)baz"
set -g default-terminal "tmux-256color"
set -g default-terminal "rxvt-unicode-256color" # better colors, for sm rsn

# Per https://superuser.com/a/1098626/26274
#   Set hosting window title to tmux/tmate internal title
set-option -g set-titles on
set-option -g set-titles-string "⁽™⁾ #T"

set-window-option -g mode-keys vi
set-option -g status-bg yellow

#   When clear-screen command rec'd, first scroll contents up into history.
set-option -g scroll-on-clear on
#   Default limit is 2000 lines, w/100 removed on hitting that liit.
set-option -g history-limit 5100
